// Automatically generated by astro-icon
// 926407b36cb91a623b31ca70885a5fde669f11ef080d28202363bb4382957dac

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "1"
		| "2"
		| "3"
		| "4"
		| "5"
		| "beach"
		| "github"
		| "linkedin"
		| "paint"
		| "web";
}