version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: xid-website
    restart: unless-stopped
    expose:
      - "4321"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8089:8089"
    volumes:
      - ./conf/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      app:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
    external: true
  caddy_config: 