version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: xid-website
    restart: unless-stopped
    ports:
      - "4321:4321"
    expose:
      - "4321"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
